complexity:
  LongParameterList:
    active: false
  LongMethod:
    active: false
  CyclomaticComplexMethod:
    threshold: 20
style:
  ReturnCount:
    active: false
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
exceptions:
  SwallowedException:
    active: false
